name: khaberny
description: "A governmental app to connect citizens, advertisers, and municipalities."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  google_fonts: ^6.2.1

  flutter_svg: ^2.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  #  Firebase dependencies (compatible versions)
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5  

  # Image picker for selecting ad images
  image_picker: ^1.0.7

  # Toast messages
  fluttertoast: ^8.2.9

  #  Charts and Progress Indicators for Ad Report
  percent_indicator: ^4.2.2
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/khaberny_background.png
    - assets/ads.jpg
    - assets/citizen.jpg
    - assets/avatar.png
    - assets/images/government.jpg

  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
